# All the default MateOS aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/mateos/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
